### ISSUE TITLE
Task: Produire un rapport sur l‘accessibilité

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#16]
# Produire un rapport sur l’accessibilité

## Epic Description
Dans le cadre de la valorisation de l’atelier, nous aimerions produire un rapport sur l’accessibilité du fleuve Saint Laurent qui pourra être intégré au wiki. Le rapport pourra être réalisé au semestre de printemps 2022.

## List of Tasks (Complete in order)
1. [ ] Task 1: Recruter une personne pour ce projet
2. [ ] Task 2: Définir les tâches à venir
3. [ ] Task 3: Définir milestones / planning
4. [ ] ...

**Comment by sjinko** [comment]
Salut @EmileForest, peux-tu me dire où nous en sommes par rapport au travail de CB?

**Comment by EmileForest** [comment]
@sjinko Je vais lui écrire cette semaine pour valider avec elle !

**Comment by EmileForest** [comment]
@sjinko Catherine n'avait pas vu mon message. Je l'ai relancé pour une rencontre. Je t'en tiens au courant. 

Je vais voir comment on peut bien valoriser tout ça !

**Comment by sjinko** [comment]
Ok, tiens moi au courant

**Comment by sjinko** [comment]
This issue is managed in #21
