### ISSUE TITLE
Vérifier la visibilité des issues associés à des projets cachés.

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#17]
Salut @iolyd, j’ai créé un projet caché, mais j’aimerais savoir si celui-ci et les issues qui lui sont associées sont visibles ou non des personnes qui n’y sont pas.

- [x] Pourrais-tu faire un screenshot de la page : https://github.com/CUPUM/ecometropole_laurentienne/projects?type=beta
- [x] Pourrais-tu prendre un screenshot de la page : https://github.com/CUPUM/ecometropole_laurentienne/issues
- [x] Et le me transmettre dans ce issue?
- [x] M’attribuer ce issue pour le suivit

**Comment by iolyd** [comment]
Page _projects_:
![image](https://user-images.githubusercontent.com/52970928/146460061-4d4ea0bd-dfd8-48e9-a8e2-1c72f624adf2.png)

Page _issues_:
![image](https://user-images.githubusercontent.com/52970928/146460091-ebaf8f9f-d4ff-4c01-8dc5-94805c6d57f3.png)

Mais je ne crois pas que c'est représentatif de ce que les autres membres voient car j'ai le statut de _owner_ au niveau de l'organisation:
![image](https://user-images.githubusercontent.com/52970928/146459998-4b77b1fd-581d-41b4-ab37-ab58a0e920d7.png)

**Comment by sjinko** [comment]
J'ai essayé en mode anonyme et ça donne la même chose. Du coup, les projets ne sont pas visibles mais les issues le restent. 

On devrait donc trouver une façon de créer des issues qui ne sont pas visibles.

@iolyd une idée?

**Comment by iolyd** [comment]
En fait, les _issues_ respectent les paramètres de visibilité du dépôt (`private` ou `public`) dans lequel ils s'inscrivent plutôt que les paramètres des projets. En réalité les projets ne font que référer des _issues_ qui existent dans le contexte d'un dépôt.

[Pour l'instant ce n'est pas possible de créer des _issues_ «confidentiels»](https://github.com/isaacs/github/issues/37)

En lisant dans la documentation, je crois comprendre que si l'on veut une gestion plus fine de _qui_ peut voir les _issues_, il faudrait vraisemblablement les organiser dans des dépôts indépendants, chacuns avec des accès attribués à des sous-groupes spécifiques.

**Comment by iolyd** [comment]
Autrement, dans ce genre de situation il serait aussi possible de fonctionner en utilisant uniquement des items de projet (_draft issues_) sans convertir ceux-ci en _issues_. Par contre, en travaillant de cette manière les items en question ne pourront pas être développés avec des commentaires comme les _issues_ traditionnels le permettent.

**Comment by sjinko** [comment]
Ok. Merci.
