### ISSUE TITLE
Task: Renomer les fichiers des images d’accompagnement

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#40]
# Task Description
J’ai réalisé trop tard que les fichiers des images d’accompagnement poussés par @maryannemonette ne respectaient pas la nomenclature:

La section ```nom_de_famille``` doit correspondre au nom de famille des auteurs des oeuvres (artistes, photographes, etc.)

Pour alléger le git, je peux m’occuper de le faire directement. @MaryanneMonette, pourrais-tu par contre m’indiquer les noms des artistes? Tu peux simplement répondre directement par retour de courriel.

# List of actions
- [x] Action: @MaryanneMonnet --> Lister le nom des artistes 
- [x] Action: @sjinko --> git rename files

**Comment by MaryanneMonette** [comment]
1.  Life without objects : lang_menking-image-life_without_objects-20220915.jpeg

  1.

Vertical Factories in Megacities : liu_xie-image-vertical_factories_in_megacities-20220915.jpeg

  2.  Déchets : nahon-image-dechets-20220915.jpeg

  3.

  4.  Human Nature : ambarzumjan-image-human_nature-20220915

  5.

  6.  Iles de la Madelaine : mount-image-iles_de_la_madelaine-20220915.jpeg

Merci pour le changement, je n'avais pas compris de cette façon.


Bonne fin de journée,

Maryanne Monette
Bachelière en urbanisme
Étudiante au 2e cycle en design urbain
________________________________
De : Shin Alexandre Koseki ***@***.***>
Envoyé : 20 septembre 2022 15:48
À : CUPUM/ecometropole_laurentienne ***@***.***>
Cc : Maryanne Monette ***@***.***>; Mention ***@***.***>
Objet : [CUPUM/ecometropole_laurentienne] Task: Renomer les fichiers des images d’accompagnement (Issue #40)


Task Description

J’ai réalisé trop tard que les fichiers des images d’accompagnement poussés par @MaryanneMonette<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaryanneMonette&data=05%7C01%7Cmaryanne.monette%40umontreal.ca%7Cff035139d93b42afb5f408da9b411702%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637993001101224466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PxUpYdcjUVDJEVOXMegBZw9O1FK3qi0jFqJVjvBzMJo%3D&reserved=0> ne respectaient pas la nomenclature:

La section ````nom_de_famille``` doit correspondre au nom de famille des auteurs des oeuvres (artistes, photographes, etc.)

Pour alléger le git, je peux m’occuper de le faire directement. Pourrais-tu parcontre inscrire ici le noms des artistes?
Tu peux simplement répondre directement par retour de courriel

List of actions

  *    Action: @MaryanneMonnet --> Lister le nom des artistes
  *    Action: @sjinko<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsjinko&data=05%7C01%7Cmaryanne.monette%40umontreal.ca%7Cff035139d93b42afb5f408da9b411702%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637993001101224466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qlCQLsfoA7cprN56PeISAWlo9vOt5zm10lCj6TweWJY%3D&reserved=0> --> git rename files
