### ISSUE TITLE
Task: Transmettre copie numérisée du reçu pour le plein d’essence

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ecometropole_laurentienne#69]
# Task Description
Bonjour @ArianeViens, pourrais-tu me transmettre la copie numérisée (PDF) du reçu pour le plein d’essence que Géraldine ou toi avez payé. Merci de m’indiquer qui a payé ce montant. 

# List of actions
- [ ] Action: Transmettre copie numérisée (PDF) du reçu
- [ ] Action: Préciser qui a payé cette facture

**Comment by ArianeViens** [comment]
[viens-desautels_recu_essence.pdf](https://github.com/CUPUM/ecometropole_laurentienne/files/9905794/viens-desautels_recu_essence.pdf)
Voilà le reçu de l'essence, c'est moi qui a payé.

**Comment by sjinko** [comment]
Super, merci. Je vais faire une demande de versement directement sur ton compte. 
PS: le nom du fichier aurait du être stady_gas_bar-recu-transport-20221028.pdf 😉
Je m’occupe d’en changer le nom, donc je ferme ce issue.
